USE [master]
GO
CREATE DATABASE [THINDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'THINDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\THINDB.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'THINDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\THINDB_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [THINDB] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [THINDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [THINDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [THINDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [THINDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [THINDB] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [THINDB] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [THINDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [THINDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [THINDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [THINDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [THINDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [THINDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [THINDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [THINDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [THINDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [THINDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [THINDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [THINDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [THINDB] SET  READ_WRITE 
GO
ALTER DATABASE [THINDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [THINDB] SET  MULTI_USER 
GO
ALTER DATABASE [THINDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [THINDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [THINDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [THINDB] SET ALLOW_SNAPSHOT_ISOLATION ON
GO
USE [THINDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [THINDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [THINDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
