USE [master]
GO
USE [THINDB]
GO
INSERT [dbo].[SVC] ([SVC_NAME], [SVC_TITLE]) VALUES (N'DESK', N'DESK')

INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerGateSecretKey', N'JuP4611KJd1dFTqenNpVPU6r', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateKeyList', N'gatekey12345', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'SmtpServerHostname', N'smtp.example.org', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'SmtpUsername', N'smtpuser', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'SmtpPassword', N'smtppassword', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'SmtpOtpFrom', N'Thin Telework Private OTP<telework@example.org>', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateSettings_Int_ReportInterval', N'1000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateSettings_Int_ReportExpires', N'20000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateSettings_Int_TunnelTimeout', N'30000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateSettings_Int_TunnelKeepAlive', N'10000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GateSettings_Int_TunnelUseAggressiveTimeout', N'1', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'TestGateTcpReachability', N'1', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'MaxSessionsPerGate', N'3000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'GatewayServicePortIpAcl', N'0.0.0.0/0', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerMaxConcurrentWpcRequestProcessingForUsers', N'500', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerDbFullReloadIntervalMsecs', N'10000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerDbWriteUpdateIntervalMsecs', N'1000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerDbBackupFileWriteIntervalMsecs', N'60000', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'QueryPassword_Stat', N'super', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'QueryPassword_Gates', N'super', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'QueryPassword_Sessions', N'super', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'AllowedProxyIpAcl', N'127.0.0.0/8', NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[VAR] ([VAR_NAME], [VAR_VALUE1], [VAR_VALUE2], [VAR_VALUE3], [VAR_VALUE4], [VAR_VALUE5], [VAR_VALUE6]) VALUES (N'ControllerRecordStatIntervalMsecs', N'600000', NULL, NULL, NULL, NULL, NULL)

